### ISSUE TITLE
Build Artifacts for v1.0.9

### ISSUE THREAD

**Issue by LukeL-dev** [trailofbits/uthenticode#73]
There are no build artifacts for v1.0.9. Do you plan on providing them?

**Comment by woodruffw** [comment]
Hmm, not sure how that happened. Thanks for reporting; we'll look into this!

In the mean time, you should try and follow the build steps if you'd like a build for that release version.

**Comment by woodruffw** [comment]
Since the library here is written in C++ and exposes a C++ interface (rather than just a "pure" C one), we've decided to stop providing build artifacts: the lack of any ABI guarantees means that we aren't confident that people can link against our built versions safely, rather than linking against their own built versions.
